title: Efemérides de Aviación
description: Archivo editorial de efemérides históricas en aviación
baseurl: "" # déjalo vacío si el sitio estará en la raíz
url: "https://efemerides-aviacion.github.io"

theme: minima
plugins:
  - jekyll-feed

