title: Efemérides de Aviación
description: Archivo editorial de efemérides históricas en aviación
baseurl: "" # vacío porque el sitio está en la raíz
url: "https://efemerides-aviacion.github.io"

theme: null
plugins:
  - jekyll-feed

